## Prepare Dataset

In [3]:
from utils.data_utils import *

In [4]:
dataset_name = 'ml_100k'
p_value = 0.05

R_bar_train, R_bar_val, R_bar_test, R_train, R_val, R_test = prepare_data(dataset_name, p_value)

In [5]:
from tensorflow.keras.optimizers import Adam
from utils.weights_utils import MatrixProcessor
from autoencoders.weighted_mse_autoencoder import UserAutoEncoder, ItemAutoEncoder

matrix_processor = MatrixProcessor()
user_matrix_multiplier = matrix_processor.compute_terms(R_bar_train)

batch_size = 32
user_dataset = tf.data.Dataset.from_tensor_slices((user_matrix_multiplier, user_matrix_multiplier))
user_dataset = user_dataset.shuffle(buffer_size=user_matrix_multiplier.shape[0]).batch(batch_size)

ae_optimizer = Adam(learning_rate=0.01)

autoencoder_X = UserAutoEncoder(user_matrix_multiplier.shape[1], 4)
autoencoder_X.compile(optimizer=ae_optimizer, loss='mse')

autoencoder_X.fit(user_dataset, validation_data=user_dataset, epochs=10, verbose=2, batch_size=batch_size, callbacks=[])

Epoch 1/10
30/30 - 3s - loss: 2369704.2500 - val_loss: 244157.0000 - 3s/epoch - 95ms/step
Epoch 2/10
30/30 - 0s - loss: 2077906.0000 - val_loss: 11678207.0000 - 153ms/epoch - 5ms/step
Epoch 3/10
30/30 - 0s - loss: 1500731.8750 - val_loss: 2853003.7500 - 159ms/epoch - 5ms/step
Epoch 4/10
30/30 - 0s - loss: 769324.1250 - val_loss: 237282.0625 - 171ms/epoch - 6ms/step
Epoch 5/10
30/30 - 0s - loss: 253514.1562 - val_loss: 1976791.5000 - 211ms/epoch - 7ms/step
Epoch 6/10
30/30 - 0s - loss: 55121.4258 - val_loss: 146477.1094 - 204ms/epoch - 7ms/step
Epoch 7/10
30/30 - 0s - loss: 12280.3496 - val_loss: 266701.9688 - 158ms/epoch - 5ms/step
Epoch 8/10
30/30 - 0s - loss: 4876.9175 - val_loss: 1069914.5000 - 170ms/epoch - 6ms/step
Epoch 9/10
30/30 - 0s - loss: 4209.5083 - val_loss: 14872.2314 - 174ms/epoch - 6ms/step
Epoch 10/10
30/30 - 0s - loss: 5225.8154 - val_loss: 2090.9375 - 181ms/epoch - 6ms/step


In [1]:
from utils.data_utils import preprocess_data

dataset = 'ml_100k'
p_value = 0.1
# Prepare dataset
R_bar_train, R_bar_val, _, _, _, _ = preprocess_data(dataset=dataset, p=p_value)

/Users/munchong/Desktop/recsys/implicit_feedback_recsys/env/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
2023-12-24 15:11:51.157949: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Data Generator

In [48]:
# import numpy as np

# # Example dummy data
# dummy_inputs = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]], dtype=np.float32)  # Shape (2, 3)
# dummy_targets = np.array([[0.2, 0.3, 0.4], [0.5, 0.6, 0.7]], dtype=np.float32)  # Shape (2, 3)
# dummy_weights = np.array([[1, 2, 1], [2, 1, 2]], dtype=np.float32)  # Shape (2, 3)

# # Convert dummy data to tensors if they are not already
# dummy_inputs = tf.convert_to_tensor(dummy_inputs)
# dummy_targets = tf.convert_to_tensor(dummy_targets)
# dummy_weights = tf.convert_to_tensor(dummy_weights)

# # Check shapes
# print("Input shape:", dummy_inputs.shape)
# print("Target shape:", dummy_targets.shape)
# print("Weights shape:", dummy_weights.shape)

import numpy as np
import tensorflow as tf

# Generate 10 dummy rows of data
dummy_inputs = np.random.rand(10, 3).astype(np.float32)  # Shape (10, 3)
#dummy_targets = np.random.rand(10, 3).astype(np.float32)  # Shape (10, 3)
dummy_weights = np.random.randint(1, 5, (10, 3)).astype(np.float32)  # Shape (10, 3)

# Convert dummy data to tensors
dummy_inputs_tensor = tf.convert_to_tensor(dummy_inputs)
dummy_targets_tensor = tf.convert_to_tensor(dummy_inputs)
dummy_weights_tensor = tf.convert_to_tensor(dummy_weights)

# Print shapes
print("Input tensor shape:", dummy_inputs_tensor.shape)
print("Target tensor shape:", dummy_targets_tensor.shape)
print("Weights tensor shape:", dummy_weights_tensor.shape)



Input tensor shape: (10, 3)
Target tensor shape: (10, 3)
Weights tensor shape: (10, 3)


In [49]:
dummy_inputs

array([[0.02102008, 0.22426595, 0.38649988],
       [0.6241214 , 0.7362278 , 0.7012032 ],
       [0.22834125, 0.28006727, 0.95931756],
       [0.3313171 , 0.7340466 , 0.4501734 ],
       [0.87129796, 0.8634871 , 0.81843334],
       [0.6178341 , 0.6822416 , 0.01459227],
       [0.94953674, 0.43377674, 0.13697594],
       [0.790288  , 0.0448177 , 0.7756005 ],
       [0.20874563, 0.9547339 , 0.3719767 ],
       [0.9862683 , 0.84811366, 0.74733883]], dtype=float32)

In [51]:
dummy_targets_tensor

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[0.02102008, 0.22426595, 0.38649988],
       [0.6241214 , 0.7362278 , 0.7012032 ],
       [0.22834125, 0.28006727, 0.95931756],
       [0.3313171 , 0.7340466 , 0.4501734 ],
       [0.87129796, 0.8634871 , 0.81843334],
       [0.6178341 , 0.6822416 , 0.01459227],
       [0.94953674, 0.43377674, 0.13697594],
       [0.790288  , 0.0448177 , 0.7756005 ],
       [0.20874563, 0.9547339 , 0.3719767 ],
       [0.9862683 , 0.84811366, 0.74733883]], dtype=float32)>

In [47]:
dummy_weights

array([[3., 1., 1.],
       [1., 4., 4.],
       [2., 3., 1.],
       [3., 3., 1.],
       [2., 4., 2.],
       [3., 4., 4.],
       [2., 3., 3.],
       [1., 2., 2.],
       [1., 4., 3.],
       [1., 4., 4.]], dtype=float32)

In [55]:
import tensorflow as tf

def data_generator(inputs, targets, weights, batch_size):
    dataset = tf.data.Dataset.from_tensor_slices((inputs, targets, weights))
    dataset = dataset.shuffle(buffer_size=len(inputs)).batch(batch_size)
    return dataset


In [56]:
train_dataset = data_generator(dummy_inputs_tensor, dummy_targets_tensor, dummy_weights_tensor, batch_size=2)
val_dataset = data_generator(R_bar_val, R_bar_val, weights, batch_size=64)  # If you have separate validation weights, use those instead


In [57]:
# Iterate over the train_dataset
for batch, (inputs, targets, batch_weights) in enumerate(train_dataset):
    print(f"Batch {batch}")
    print("Inputs:", inputs.numpy())
    print("Targets:", targets.numpy())
    print("Weights:", batch_weights.numpy())
    # Break after the first iteration for demonstration purposes
    # Remove the following line to iterate over the whole dataset
    break

Batch 0
Inputs: [[0.22834125 0.28006727 0.95931756]
 [0.94953674 0.43377674 0.13697594]]
Targets: [[0.22834125 0.28006727 0.95931756]
 [0.94953674 0.43377674 0.13697594]]
Weights: [[4. 4. 2.]
 [4. 2. 4.]]


## Compute Weighted Matrix

In [10]:
import tensorflow as tf
import os
from scipy.linalg import svd

class MatrixProcessor:
    def __init__(self):
        pass
    
    @staticmethod
    def compute_probabilities(matrix):
        # Sum the entries in each row
        row_sums = tf.reduce_sum(matrix, axis=1)

        # Total sum of entries in the matrix
        total_entries = tf.reduce_sum(matrix)

        # Compute empirical probabilities
        p_hat = row_sums / total_entries

        # Compute smoothed probabilities
        m = matrix.shape[0]  # Number of rows in the matrix
        p_check = 0.5 * (p_hat + (1/m))

        return p_hat, p_check

    @staticmethod
    def compute_terms(matrix):
        # Compute the empirical and smoothed probabilities
        p_hat, p_check = MatrixProcessor.compute_probabilities(matrix)
        q_hat, q_check = MatrixProcessor.compute_probabilities(tf.transpose(matrix))

        # Convert the probabilities to diagonal matrices
#         diagonal_P = tf.cast(tf.linalg.diag(p_hat), dtype=tf.float32)
#         diagonal_Q = tf.cast(tf.linalg.diag(q_hat), dtype=tf.float32)
#         P_check = tf.cast(tf.linalg.diag(p_check), dtype=tf.float32)
#         Q_check = tf.cast(tf.linalg.diag(q_check), dtype=tf.float32)

        # Compute new matrix
        p_check_matrix = tf.tile(tf.expand_dims(p_check, 1), [1, len(q_check)])
        q_check_matrix = tf.tile(tf.expand_dims(q_check, 0), [len(p_check), 1])
        new_matrix = tf.math.rsqrt(p_check_matrix * q_check_matrix)

        return new_matrix

    @staticmethod
    def compute_svd(matrix, latent_dim):
        # Compute the SVD and save the first k singular vectors/values
        U, s, Vt = svd(matrix, full_matrices=False)

        X = tf.cast(U[:, :latent_dim], dtype=tf.float32)
        Y = tf.cast(Vt[:latent_dim, :].T, dtype=tf.float32)

        return X, Y
    

In [11]:
weights = MatrixProcessor.compute_terms(R_bar_train)


## Weighted Autoencoder Training

In [1]:
import numpy as np
import tensorflow as tf
import random
import os

def reset_random_seeds():
   os.environ['PYTHONHASHSEED']=str(1)
   tf.random.set_seed(1)
   np.random.seed(1)
   random.seed(1)

reset_random_seeds()


/Users/munchong/Desktop/recsys/implicit_feedback_recsys/env/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [2]:
from autoencoders.weighted_autoencoder import WeightedUserAutoEncoder, WeightedItemAutoEncoder, CustomLoss

import numpy as np

# Example dummy data
num_samples = 5
input_feature_len = 2  # Adjust as per your actual feature length

# Create dummy data
inputs = np.random.random((num_samples, input_feature_len))
targets = np.random.random((num_samples, input_feature_len))
weights = np.random.random((num_samples, input_feature_len))

batch_size = 5  # Adjust batch size as needed

def data_generator(inputs, targets, batch_size):
    dataset = tf.data.Dataset.from_tensor_slices((inputs, targets))
    dataset = dataset.shuffle(buffer_size=len(inputs)).batch(batch_size)
    return dataset

train_dataset = data_generator(inputs, inputs, batch_size)

2023-12-25 14:20:24.985754: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
# R_bar_train_weighted = MatrixProcessor.compute_terms(inputs)

In [4]:
# train_dataset = data_generator(R_bar_train_weighted, R_bar_train_weighted, batch_size)

In [13]:
import numpy as np
import tensorflow as tf
import random
import os
# os.environ['TF_DETERMINISTIC_OPS'] = '1'

# # Set seeds
# seed_value = 42
# tf.random.set_seed(seed_value)
# np.random.seed(seed_value)
# random.seed(seed_value)
class LossHistory(tf.keras.callbacks.Callback):
    def on_train_batch_end(self, batch, logs=None):
        print('Logs :', logs)
        #print(f"Training: Batch {batch}, Loss {logs['batch_loss']}")

autoencoder = WeightedUserAutoEncoder(input_feature_len, 2, [2], [input_feature_len], 0.001, 0.1, False)
autoencoder.compile(optimizer='adam', loss=tf.keras.losses.MeanSquaredError(), metrics=['mse'])

In [14]:
inputs

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01]])

In [15]:
autoencoder.fit(train_dataset, 
                epochs=2, 
                # batch_size=128,
                validation_data=train_dataset, 
                verbose=2,
                shuffle=True,
                callbacks=[LossHistory()])

Epoch 1/2
Logs : {'mse': 0.15510718524456024}
1/1 - 0s - mse: 0.1551 - val_loss: 0.1697 - val_mse: 0.1649 - 405ms/epoch - 405ms/step
Epoch 2/2
Logs : {'mse': 0.16879650950431824}
1/1 - 0s - mse: 0.1688 - val_loss: 0.1677 - val_mse: 0.1629 - 10ms/epoch - 10ms/step


In [9]:
import tensorflow as tf

epochs = 1
total_loss = 0
num_batches = 0

reset_random_seeds()

for epoch in range(epochs):
    print(f"Epoch {epoch + 1}/{epochs}")
    for step, (x_batch_train, y_batch_train) in enumerate(train_dataset):
        with tf.GradientTape() as tape:
            predictions = autoencoder(x_batch_train, training=True)

            # Ensure y_batch_train is of the same type as predictions
            y_batch_train = tf.cast(y_batch_train, tf.float32)

            # Custom computation of squared error
            squared_difference = tf.square(y_batch_train - predictions)
            # Compute the batch loss
            batch_loss = tf.reduce_sum(squared_difference) / tf.cast(tf.size(y_batch_train), dtype=tf.float32)

        #grads = tape.gradient(batch_loss, autoencoder.trainable_variables)
        #autoencoder.optimizer.apply_gradients(zip(grads, autoencoder.trainable_variables))

        print('X batch train :', x_batch_train)
        print('y batch train :', y_batch_train)
        print('predictions :', predictions)
        print(f"Batch {step}, Loss: {batch_loss.numpy()}")
        # Accumulate average batch loss
        total_loss += batch_loss
        num_batches += 1

    # Compute average loss over all batches
    avg_loss_per_epoch = total_loss / num_batches
    print(f"Average Loss for Epoch {epoch + 1}: {avg_loss_per_epoch.numpy()}")


Epoch 1/1
X batch train : tf.Tensor(
[[1.46755891e-01 9.23385948e-02]
 [4.17022005e-01 7.20324493e-01]
 [1.14374817e-04 3.02332573e-01]
 [1.86260211e-01 3.45560727e-01]
 [3.96767474e-01 5.38816734e-01]], shape=(5, 2), dtype=float64)
y batch train : tf.Tensor(
[[1.46755889e-01 9.23385918e-02]
 [4.17021990e-01 7.20324516e-01]
 [1.14374816e-04 3.02332580e-01]
 [1.86260208e-01 3.45560730e-01]
 [3.96767467e-01 5.38816750e-01]], shape=(5, 2), dtype=float32)
predictions : tf.Tensor(
[[-0.06717951  0.01890692]
 [-0.278314    0.03892186]
 [-0.05775178 -0.00975677]
 [-0.04371599 -0.02262597]
 [-0.23682646  0.0417682 ]], shape=(5, 2), dtype=float32)
Batch 0, Loss: 0.19366595149040222
Average Loss for Epoch 1: 0.19366595149040222


In [11]:
np.sum(np.array([[-0.06717951,  0.01890692],
 [-0.278314,    0.03892186],
 [-0.05775178, -0.00975677],
 [-0.04371599, -0.02262597],
 [-0.23682646,  0.0417682 ]]))

-0.6165734999999999